# This is a TOML document. Boom
[env]
     Region = "china"
  Zone = "gd"
  # Host = "discovery"
  DeployEnv = "dev"
 Env = "dev"
        weight = 10

[discovery]
    nodes = ["127.0.0.1:7171"]
     Region = "china"
  Zone = "gd"
  Host = "discovery"
  DeployEnv = "dev"
 Env = "dev"
[kafka]
    topic = "goim-push-topic"
    group = "goim-push-group-job"
    brokers = ["127.0.0.1:9092"]
